#!/bin/bash
set -o errexit -o nounset -o pipefail

# Command line parameter parsing and dependency checks.
function desc  { echo "Create a SSH RSA key with high security margin"; }
function usage { echo "Usage: $(basename ${0})"; }
if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
OK=1; which ssh-keygen > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "cryptsetup not found"; exit 1; fi


KEY_BITS="4096"
# KEY_BITS="8192"
# KEY_BITS="16384"

ssh-keygen -t rsa -b "${KEY_BITS}"
