#!/bin/bash
set -o errexit -o nounset -o pipefail

# Command line parameter parsing and dependency checks.
function desc  { echo "Strip as many unused symbols from a binary as possible"; }
function usage { echo "Usage: $(basename ${0}) INPUT_FILE"; }
if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
OK=1; which strip > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "strip not found"; exit 1; fi


if [ ${#} -eq 0 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi

strip --strip-all --discard-all ${*}
