#!/bin/bash
set -o errexit -o nounset -o pipefail

# Command line parameter parsing and dependency checks.
function desc  { echo "Runs flif with slowest settings to archieve maximum flif image file compression"; }
function usage { echo "Usage: $(basename ${0}) PNG_INPUT_FILE"; }
if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
OK=1; which flif > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "flif not found"; exit 1; fi


if [ ${#} -ne 2 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi

flif -e --no-interlace --effort=100 "${1}" "${2}"
