#!/bin/bash
set -o errexit -o nounset -o pipefail

# Command line parameter parsing and dependency checks.
function desc  { echo "xz with parameters for maximum compression"; }
function usage { echo "Usage: $(basename ${0}) FILE_TO_COMPRESS"; }
if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
OK=1; which optipng > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "optipng not found"; exit 1; fi


if [ ${#} -eq 0 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi

xz --lzma2=nice=273 -9 -e -v ${*}
# xz -9 -e -v --lzma2=nice=273,depth=1000 ${*}
