#!/bin/bash
set -o errexit -o nounset -o pipefail

# Command line parameter parsing and dependency checks.
function desc  { echo "Runs the valgrind memcheck tool with settings for to find maximum numbers of errors"; }
function usage { echo "Usage: $(basename ${0}) EXECUTABLE"; }
if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
OK=1; which valgrind > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "valgrind not found"; exit 1; fi


if [ ${#} -ne 1 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi

EXECUTABLE=${1}
TOOL_OPTIONS="--tool=memcheck --leak-check=full --track-origins=yes --show-reachable=yes --show-leak-kinds=all --errors-for-leak-kinds=all"
GLOBAL_OPTION="-q --error-exitcode=9 --trace-children=yes --num-callers=50"

valgrind ${GLOBAL_OPTION} ${TOOL_OPTIONS} ${EXECUTABLE}
