#!/bin/bash
set -o errexit -o nounset -o pipefail

# Command line parameter parsing and dependency checks.
function desc  { echo "Create a LUKS dm-crypt volume with very secure crypto/hash settings"; }
function usage { echo "Usage: $(basename ${0}) BLOC_DEVICE"; }
if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
# We cannot check the cyptsetup binary as we are not root yet.
# OK=1; which cryptsetup > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "cryptsetup not found"; exit 1; fi


if [ ${#} -ne 1 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi

BLOCK_DEVICE=${1}
# Select a random iter-time between 5000 and 5499
MINIMUM_ITER_TIME=5000
MAX_ITER_TIME_RAND=500
ITER_TIME="$(( ( RANDOM % MAX_ITER_TIME_RAND ) + MINIMUM_ITER_TIME ))"

echo "Set \"iter-time\" to ${ITER_TIME}"

if [ $(id -u) -ne 0 ]; then echo "Root passwort required."; fi
su - -c "cryptsetup luksFormat    ${BLOCK_DEVICE}     \
             --cipher             serpent-xts-plain64 \
             --key-size           512                 \
             --hash               sha512              \
             --iter-time          ${ITER_TIME}        \
             --verify-passphrase"
