#!/bin/bash
set -o errexit -o nounset -o pipefail

# Command line parameter parsing and dependency checks.
function desc  { echo "Create an encrypted partition with LUKS header"; }
function usage { echo "Usage: $(basename ${0}) BLOC_DEVICE"; }
if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
OK=1; cryptsetup > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "cryptsetup not found"; exit 1; fi


if [ ${#} -ne 1 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi

BLOCK_DEVICE=${1}

cryptsetup luksFormat    ${BLOCK_DEVICE}            \
           --cipher             twofish-xts-plain64 \
           --key-size           512                 \
           --hash               sha512              \
           --iter-time          5432                \
           --verify-passphrase
}
