#!/bin/bash
set -o errexit -o nounset -o pipefail

# Command line parameter parsing and dependency checks.
function desc  { echo "Runs optipng with slowest settings to archieve maximum PNG file compression."; }
function usage { echo "Usage: optipng PNG_INPUT_FILE"; }
if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
OK=1; which optipng > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "optipng not found"; exit 1; fi


if [ ${#} -ne 1 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi

optipng -o7 ${1}
