#!/bin/bash
set -o errexit -o nounset -o pipefail

# Command line parameter parsing and dependency checks.
function desc  { echo "sshfs ith parameters for faster connection and lower latency"; }
function usage { echo "Usage: $(basename ${0}) AUDIO_INPUT_FILE"; }
if [ ${#} -eq 1 ]; then if [ ${1} = "-h" -o ${1} = "--help" ]; then desc; echo; usage; exit 0; fi; fi
OK=1; which flac > /dev/null || OK=0; if [ ${OK} -ne 1 ]; then echo "flac not found"; exit 1; fi


if [ ${#} -lt 1 ]; then echo "Wrong number of arguments."; echo; usage; exit 1; fi


sshfs -C \
      -o noatime \
      -o compression=no \
      -o reconnect \
      -o auto_cache \
      -o cache_timeout=115200 \
      -o cache_stat_timeout=115200 \
      -o cache_dir_timeout=115200 \
      -o cache_link_timeout=115200 \
      -o attr_timeout=115200 \
      -o ac_attr_timeout=115200 \
      -o no_readahead -f $*
